import { DocXIcon, GithubIcon, GoogleIcon, TXTIcon } from '@/assets/svgs';
import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  CrossIcon,
  DownloadIcon,
  Edit,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  LucideShoppingBag,
  MessageSquare,
  Moon,
  MoreVertical,
  PauseIcon,
  Pizza,
  PlayIcon,
  Plus,
  SaveIcon,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  UploadIcon,
  User,
  UserCircle2Icon,
  UserPen,
  UserX2Icon,
  WandIcon,
  X
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  wand: WandIcon,
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  product: LucideShoppingBag,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle2Icon,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: GithubIcon,
  google: GoogleIcon,
  docx: DocXIcon,
  txt: TXTIcon,
  twitter: Twitter,
  check: Check,
  cross: CrossIcon,
  upload: UploadIcon,
  play: PlayIcon,
  download: DownloadIcon,
  edit: Edit,
  pause: PauseIcon,
  save: SaveIcon,
  messageSquare: MessageSquare
};
